name: dfl2dsl
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.7
  - black
  - cairocffi
  - cffi
  - dill
  - frozendict
  - graphviz
  - imageio
  - jupyterlab
  - matplotlib
  - multiprocess
  - nltk
  - num2words
  - numpy
  - openai=0.27.7
  - pandas
  - pathos
  - Pillow
  - pip
  - pre-commit
  - pycairo
  - Pygments
  - pytest
  - python-dateutil
  - pytorch
  - regex
  - scikit-learn
  - scipy
  - seaborn
  - sexpdata
  - toml
  - tqdm
  - transformers
  - tokenizers=0.10.3
  - typing-extensions
  - sqlalchemy
  - python-levenshtein
  - pip:
    - mypy-extensions
    - phx-class-registry
    - pytorch-nlp
    - stitch_core
